#!/usr/bin/env python
""" 
Scripts for calculating cell population
given differentially expressed genes.
"""
__author__    = "Edward Wijaya <ewijaya@gmail.com>"
__copyright__ = "Copyright 2015"
import csv
import json
import argparse
import sys  
import os
this_path = os.path.abspath(__file__)
package_path = "/".join(this_path.split("/")[0:6])
sys.path.append(package_path)
from icepop import input_reader as ir
from icepop import species_cell_proportion as scp
from icepop import enumerate_output as eo


def main():
    parser = argparse.ArgumentParser(description='''Cell population score for
            differentially expressed genes.''')
    parser.add_argument("filename", nargs='?',help="DEGs file in TSV, CSV or Excel format") 
    parser.add_argument("-s","-species",metavar="",help="species (mouse, human)",type=str,default='mouse')
    parser.add_argument("-g","-organs",metavar="",help="organs ('no_pref','bone_marrow', etc)",type=str,default='no_pref')
    parser.add_argument("-o","-outfile",metavar="",help="output file in JSON format",type=str,default='outfile.json')
    parser.add_argument("--gene_count", help="normalized score by gene_count",action="store_true")
    parser.add_argument("--logscale", help="perform log scale on FC or expression",action="store_true")

    args = parser.parse_args()
    deg_infile = args.filename
    species    = args.s
    out_json   = args.o
    organs     = args.g
    gene_count = args.gene_count
    logscale   = args.logscale

    foldchange_range=[1.5,2,2.5,3,3.5,4,4.5,5]
    fcstr = [str(x) for x in foldchange_range]
    fcstr = ",".join(fcstr)

    # Sanity check
    if organs != 'no_pref' and species == "human":
        sys.exit("Human has no organs based proportion data.")
    else:
        sys.stderr.write("Generating JSON file for the following fold changes:\n")
        sys.stderr.write(fcstr +  "\n")    
        sys.stderr.write("Output file: " +  out_json +  "\n")    
        sys.stderr.write("Gene count: " +  str(gene_count) +  "\n")    


    
    indf            = ir.read_file(deg_infile, mode="DEG")

    # cellpop_df    = scp.get_prop(species=species,mode="pandas_df")

    cellpop_df = None
    if organs == 'no_pref':
        cellpop_df = ir.read_hdf(species=species)
    else:
        cellpop_df = ir.read_hdf(species=species,organs=True)
        organ_list = list(cellpop_df.columns.levels[0])
        
        if organs not in organ_list:
            organlstr = ",".join(organ_list)
            sys.exit("organs should be in this list: " + organlstr + "\n")
            sys.exit("now *no_pref* instead \n")

        organlist = cellpop_df.columns.values.tolist()
        cellpop_df = scp.choose_organ(cellpop_df, organs)

    # print cellpop_df.head()

    eo.enumerate_output(cellpop_df, indf, fc_range = foldchange_range, \
                        outfilename = out_json,  gene_count=gene_count,
                        logscale=logscale)




if __name__ == '__main__':
    main()
